export const SHOP_TEXT = {
  detailTitle: "店舗詳細",
  accessLabel: "アクセス",
  addressLabel: "住所",
  openLabel: "営業時間",
  openStatusOpen: "営業中",
  openStatusClosed: "営業時間外",
  todayHoursPrefix: "本日",
  closedDayLabel: "定休日",
  descriptionLabel: "店舗説明",
  hoursExpandLabel: "営業時間の詳細を表示",
  hoursCollapseLabel: "営業時間を閉じる",
  mapLabel: "地図",
  favoriteLabel: "お気に入り",
  showDetail: "詳細を見る",
  backToList: "一覧へ戻る",
  directionsAction: "経路",
  hotpepperAction: "予約・公式",
  shareAction: "共有",
  shareCopied: "コピーしました",
  sharedShopNotFound: "お店を読み込めませんでした。",
  locationSectionLabel: "場所",
  hoursSectionLabel: "営業時間",
  featuresSectionLabel: "設備・サービス",
} as const;
